export const LANGUAGES = [
  {
    id: 'es',
    code: 'es',
    name: 'Spanish',
    nativeName: 'Español',
    flag: '🇪🇸',
    direction: 'ltr',
    speakers: '543M',
    learners: '21M+',
    difficulty: 'Easy for English speakers',
    description: 'Spanish is the second most spoken language by native speakers. Romantic, rhythmic, and widely used across the Americas and Spain.',
    features: ['Speaking', 'Listening', 'Reading', 'Writing', 'Grammar', 'Vocabulary'],
    color: 'bg-amber-500',
    lightColor: 'bg-amber-50',
    darkColor: 'bg-amber-600',
    levels: [
      { name: 'Beginner A1', lessons: 30, hours: 15, description: 'Basic greetings and introductions' },
      { name: 'Elementary A2', lessons: 45, hours: 22, description: 'Daily conversations and routines' },
      { name: 'Intermediate B1', lessons: 60, hours: 30, description: 'Work and travel situations' },
      { name: 'Upper Intermediate B2', lessons: 60, hours: 30, description: 'Complex topics and discussions' },
      { name: 'Advanced C1', lessons: 50, hours: 25, description: 'Professional and academic Spanish' },
      { name: 'Proficient C2', lessons: 40, hours: 20, description: 'Mastery of Spanish language' },
    ],
    wordsToLearn: 3000,
    timeToFluency: '6-12 months',
  },
  {
    id: 'fr',
    code: 'fr',
    name: 'French',
    nativeName: 'Français',
    flag: '🇫🇷',
    direction: 'ltr',
    speakers: '300M',
    learners: '19M+',
    difficulty: 'Moderate for English speakers',
    description: 'French is the language of love, diplomacy, and culture. Spoken across 5 continents, it opens doors to art, fashion, and international relations.',
    features: ['Speaking', 'Listening', 'Reading', 'Writing', 'Grammar', 'Pronunciation'],
    color: 'bg-blue-500',
    lightColor: 'bg-blue-50',
    darkColor: 'bg-blue-600',
    levels: [
      { name: 'Beginner A1', lessons: 30, hours: 15, description: 'Basic greetings and introductions' },
      { name: 'Elementary A2', lessons: 45, hours: 22, description: 'Daily conversations and routines' },
      { name: 'Intermediate B1', lessons: 60, hours: 30, description: 'Work and travel situations' },
      { name: 'Upper Intermediate B2', lessons: 60, hours: 30, description: 'Complex topics and discussions' },
      { name: 'Advanced C1', lessons: 50, hours: 25, description: 'Professional and academic French' },
      { name: 'Proficient C2', lessons: 40, hours: 20, description: 'Mastery of French language' },
    ],
    wordsToLearn: 3000,
    timeToFluency: '6-12 months',
  },
  {
    id: 'de',
    code: 'de',
    name: 'German',
    nativeName: 'Deutsch',
    flag: '🇩🇪',
    direction: 'ltr',
    speakers: '132M',
    learners: '13M+',
    difficulty: 'Challenging for English speakers',
    description: 'German is the most widely spoken language in Europe. Known for its compound words and precise grammar, it\'s essential for business and engineering.',
    features: ['Grammar', 'Vocabulary', 'Speaking', 'Listening', 'Reading', 'Writing'],
    color: 'bg-slate-500',
    lightColor: 'bg-slate-100',
    darkColor: 'bg-slate-600',
    levels: [
      { name: 'Beginner A1', lessons: 35, hours: 18, description: 'Basic greetings and introductions' },
      { name: 'Elementary A2', lessons: 50, hours: 25, description: 'Daily conversations and routines' },
      { name: 'Intermediate B1', lessons: 65, hours: 33, description: 'Work and travel situations' },
      { name: 'Upper Intermediate B2', lessons: 65, hours: 33, description: 'Complex topics and discussions' },
      { name: 'Advanced C1', lessons: 55, hours: 28, description: 'Professional and academic German' },
      { name: 'Proficient C2', lessons: 45, hours: 23, description: 'Mastery of German language' },
    ],
    wordsToLearn: 3000,
    timeToFluency: '8-14 months',
  },
  {
    id: 'it',
    code: 'it',
    name: 'Italian',
    nativeName: 'Italiano',
    flag: '🇮🇹',
    direction: 'ltr',
    speakers: '68M',
    learners: '8M+',
    difficulty: 'Easy for English speakers',
    description: 'Italian is a melodic Romance language spoken in Italy and Switzerland. Perfect for art lovers, food enthusiasts, and history buffs.',
    features: ['Speaking', 'Listening', 'Pronunciation', 'Grammar', 'Vocabulary', 'Culture'],
    color: 'bg-green-500',
    lightColor: 'bg-green-50',
    darkColor: 'bg-green-600',
    levels: [
      { name: 'Beginner A1', lessons: 28, hours: 14, description: 'Basic greetings and introductions' },
      { name: 'Elementary A2', lessons: 42, hours: 21, description: 'Daily conversations and routines' },
      { name: 'Intermediate B1', lessons: 55, hours: 28, description: 'Work and travel situations' },
      { name: 'Upper Intermediate B2', lessons: 55, hours: 28, description: 'Complex topics and discussions' },
      { name: 'Advanced C1', lessons: 45, hours: 23, description: 'Professional and academic Italian' },
      { name: 'Proficient C2', lessons: 35, hours: 18, description: 'Mastery of Italian language' },
    ],
    wordsToLearn: 2500,
    timeToFluency: '6-10 months',
  },
  {
    id: 'pt',
    code: 'pt',
    name: 'Portuguese',
    nativeName: 'Português',
    flag: '🇵🇹',
    direction: 'ltr',
    speakers: '250M',
    learners: '7M+',
    difficulty: 'Easy-Moderate for English speakers',
    description: 'Portuguese is the fastest-growing European language. Spoken in Portugal, Brazil, and African nations, it offers access to diverse cultures.',
    features: ['Speaking', 'Listening', 'Reading', 'Writing', 'Vocabulary', 'Culture'],
    color: 'bg-red-500',
    lightColor: 'bg-red-50',
    darkColor: 'bg-red-600',
    levels: [
      { name: 'Beginner A1', lessons: 30, hours: 15, description: 'Basic greetings and introductions' },
      { name: 'Elementary A2', lessons: 45, hours: 22, description: 'Daily conversations and routines' },
      { name: 'Intermediate B1', lessons: 60, hours: 30, description: 'Work and travel situations' },
      { name: 'Upper Intermediate B2', lessons: 60, hours: 30, description: 'Complex topics and discussions' },
      { name: 'Advanced C1', lessons: 50, hours: 25, description: 'Professional and academic Portuguese' },
      { name: 'Proficient C2', lessons: 40, hours: 20, description: 'Mastery of Portuguese language' },
    ],
    wordsToLearn: 2800,
    timeToFluency: '6-12 months',
  },
  {
    id: 'ja',
    code: 'ja',
    name: 'Japanese',
    nativeName: '日本語',
    flag: '🇯🇵',
    direction: 'ltr',
    speakers: '130M',
    learners: '5M+',
    difficulty: 'Very challenging for English speakers',
    description: 'Japanese combines three writing systems with unique grammar. Essential for business, anime, manga, and understanding Japanese culture.',
    features: ['Hiragana', 'Katakana', 'Kanji', 'Speaking', 'Listening', 'Reading'],
    color: 'bg-pink-500',
    lightColor: 'bg-pink-50',
    darkColor: 'bg-pink-600',
    levels: [
      { name: 'Beginner A1', lessons: 50, hours: 40, description: 'Hiragana, Katakana, basic phrases' },
      { name: 'Elementary A2', lessons: 70, hours: 56, description: 'Basic grammar and 150 Kanji' },
      { name: 'Intermediate B1', lessons: 90, hours: 72, description: 'Complex grammar and 300 Kanji' },
      { name: 'Upper Intermediate B2', lessons: 100, hours: 80, description: 'Advanced grammar and 500 Kanji' },
      { name: 'Advanced C1', lessons: 80, hours: 64, description: 'Business Japanese and 800 Kanji' },
      { name: 'Proficient C2', lessons: 60, hours: 48, description: 'Mastery of all 1000+ Kanji' },
    ],
    wordsToLearn: 2000,
    timeToFluency: '18-36 months',
  },
  {
    id: 'ko',
    code: 'ko',
    name: 'Korean',
    nativeName: '한국어',
    flag: '🇰🇷',
    direction: 'ltr',
    speakers: '82M',
    learners: '4M+',
    difficulty: 'Challenging for English speakers',
    description: 'Korean features a unique writing system (Hangul) and polite speech levels. Perfect for K-pop fans, drama lovers, and business in Korea.',
    features: ['Hangul', 'Speaking', 'Listening', 'Grammar', 'Vocabulary', 'Culture'],
    color: 'bg-purple-500',
    lightColor: 'bg-purple-50',
    darkColor: 'bg-purple-600',
    levels: [
      { name: 'Beginner A1', lessons: 40, hours: 30, description: 'Hangul alphabet and basic phrases' },
      { name: 'Elementary A2', lessons: 55, hours: 44, description: 'Daily conversations and polite speech' },
      { name: 'Intermediate B1', lessons: 70, hours: 56, description: 'Complex conversations and situations' },
      { name: 'Upper Intermediate B2', lessons: 75, hours: 60, description: 'Advanced grammar and expressions' },
      { name: 'Advanced C1', lessons: 60, hours: 48, description: 'Professional Korean and business' },
      { name: 'Proficient C2', lessons: 50, hours: 40, description: 'Mastery of Korean language' },
    ],
    wordsToLearn: 2000,
    timeToFluency: '12-24 months',
  },
  {
    id: 'zh',
    code: 'zh',
    name: 'Chinese (Mandarin)',
    nativeName: '中文',
    flag: '🇨🇳',
    direction: 'ltr',
    speakers: '1.1B',
    learners: '30M+',
    difficulty: 'Very challenging for English speakers',
    description: 'Mandarin Chinese is the world\'s most spoken language by total speakers. Tonal language with thousands of characters opens doors to business in China.',
    features: ['Pinyin', 'Characters', 'Tones', 'Speaking', 'Listening', 'Reading'],
    color: 'bg-red-600',
    lightColor: 'bg-red-50',
    darkColor: 'bg-red-700',
    levels: [
      { name: 'Beginner A1', lessons: 60, hours: 60, description: 'Pinyin, tones, basic characters' },
      { name: 'Elementary A2', lessons: 80, hours: 80, description: 'Daily life characters and phrases' },
      { name: 'Intermediate B1', lessons: 100, hours: 100, description: 'Extended vocabulary and grammar' },
      { name: 'Upper Intermediate B2', lessons: 120, hours: 120, description: 'Complex sentences and 1000+ characters' },
      { name: 'Advanced C1', lessons: 100, hours: 100, description: 'Business Chinese and 2000+ characters' },
      { name: 'Proficient C2', lessons: 80, hours: 80, description: 'Mastery of 3000+ characters' },
    ],
    wordsToLearn: 3000,
    timeToFluency: '24-48 months',
  },
  {
    id: 'ru',
    code: 'ru',
    name: 'Russian',
    nativeName: 'Русский',
    flag: '🇷🇺',
    direction: 'ltr',
    speakers: '258M',
    learners: '3M+',
    difficulty: 'Very challenging for English speakers',
    description: 'Russian is a Slavic language with complex grammar and Cyrillic script. Strategic language for business, diplomacy, and literature lovers.',
    features: ['Cyrillic', 'Grammar', 'Speaking', 'Listening', 'Reading', 'Vocabulary'],
    color: 'bg-blue-700',
    lightColor: 'bg-blue-50',
    darkColor: 'bg-blue-800',
    levels: [
      { name: 'Beginner A1', lessons: 45, hours: 35, description: 'Cyrillic alphabet and basics' },
      { name: 'Elementary A2', lessons: 60, hours: 48, description: 'Daily conversations and cases' },
      { name: 'Intermediate B1', lessons: 80, hours: 64, description: 'Complex grammar and vocabulary' },
      { name: 'Upper Intermediate B2', lessons: 85, hours: 68, description: 'Advanced grammar and discussions' },
      { name: 'Advanced C1', lessons: 70, hours: 56, description: 'Professional and academic Russian' },
      { name: 'Proficient C2', lessons: 55, hours: 44, description: 'Mastery of Russian language' },
    ],
    wordsToLearn: 3000,
    timeToFluency: '12-24 months',
  },
  {
    id: 'ar',
    code: 'ar',
    name: 'Arabic',
    nativeName: 'العربية',
    flag: '🇸🇦',
    direction: 'rtl',
    speakers: '420M',
    learners: '4M+',
    difficulty: 'Very challenging for English speakers',
    description: 'Arabic is spoken across 25 countries with Modern Standard Arabic. Essential for business, diplomacy, and understanding rich cultural heritage.',
    features: ['Alphabet', 'Reading', 'Writing', 'Speaking', 'Listening', 'Culture'],
    color: 'bg-emerald-600',
    lightColor: 'bg-emerald-50',
    darkColor: 'bg-emerald-700',
    levels: [
      { name: 'Beginner A1', lessons: 50, hours: 50, description: 'Arabic alphabet and sounds' },
      { name: 'Elementary A2', lessons: 65, hours: 65, description: 'Basic sentences and vocabulary' },
      { name: 'Intermediate B1', lessons: 85, hours: 85, description: 'Conversations and grammar' },
      { name: 'Upper Intermediate B2', lessons: 90, hours: 90, description: 'Complex topics and media' },
      { name: 'Advanced C1', lessons: 75, hours: 75, description: 'Professional and academic Arabic' },
      { name: 'Proficient C2', lessons: 60, hours: 60, description: 'Mastery of Classical and Modern Arabic' },
    ],
    wordsToLearn: 3000,
    timeToFluency: '18-36 months',
  },
] as const

export const LEARNING_FEATURES = [
  {
    icon: '🎯',
    title: 'Personalized Learning',
    description: 'AI adapts to your pace and style',
  },
  {
    icon: '🏆',
    title: 'Gamified Progress',
    description: 'Earn XP, streaks, and achievements',
  },
  {
    icon: '🎤',
    title: 'Speech Recognition',
    description: 'Practice pronunciation with AI feedback',
  },
  {
    icon: '📱',
    title: 'Learn Anywhere',
    description: 'Mobile app with offline mode',
  },
  {
    icon: '👥',
    title: 'Live Classes',
    description: 'Join sessions with native speakers',
  },
  {
    icon: '📊',
    title: 'Track Progress',
    description: 'Track progress with detailed analytics and insights',
  },
]

export const STATS = [
  { value: '10+', label: 'Languages' },
  { value: '2M+', label: 'Learners' },
  { value: '50M+', label: 'Lessons Completed' },
  { value: '98%', label: 'Satisfaction Rate' },
]

export const PRICING = [
  {
    name: 'Free',
    price: '$0',
    period: 'forever',
    description: 'Perfect for getting started',
    features: [
      '5 lessons per day',
      'Basic exercises',
      'Progress tracking',
      'Community forums',
    ],
    cta: 'Get Started',
    popular: false,
  },
  {
    name: 'Pro',
    price: '$19.99',
    period: 'month',
    description: 'Best for serious learners',
    features: [
      'Unlimited lessons',
      'AI-powered learning',
      'Speech recognition',
      'Offline mode',
      'Detailed analytics',
      'Priority support',
    ],
    cta: 'Start Free Trial',
    popular: true,
  },
  {
    name: 'Team',
    price: '$49.99',
    period: 'month',
    description: 'For businesses and schools',
    features: [
      'Everything in Pro',
      'Up to 10 members',
      'Admin dashboard',
      'Team challenges',
      'Custom content',
      'Dedicated support',
    ],
    cta: 'Contact Sales',
    popular: false,
  },
]
